project:
  type: website
  output-dir: _site
  resources:
    - styles.css
    - preview.js
    - gradient_descent.html
    - images/
    - hedlin_cv.pdf


website:
  title: "Erik Hedlin"
  navbar: false

format:
  html:
    theme: none
    css: styles.css
    include-after-body: 
      - preview.js
    minimal: true

# Default: execute code and cache/freeze outputs locally.
execute:
  freeze: auto

# CI profile: don't execute notebooks, just use frozen outputs.
# Use by setting QUARTO_PROFILE=ci (configured in GitHub Actions).
profiles:
  - id: ci
    execute:
      enabled: false
      freeze: auto
